services:
  postgres:
    image: postgres:16
    container_name: burger_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: burger_db
      POSTGRES_USER: burger_user
      POSTGRES_PASSWORD: burger_pass
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U burger_user -d burger_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
